### ISSUE TITLE
Alternative 'a'

### ISSUE THREAD

**Issue by vilav** [sora-xor/sora-font#10]
Tried blending Sora's 'a' with an alternative 'a' glyph from another typeface on Google Fonts called Epilogue.

Actually looks good. Might be worth considering in future versions perhaps?
![Screenshot 2020-08-15 at 5 21 07 PM](https://user-images.githubusercontent.com/849098/90309586-75673d80-df1c-11ea-8331-64c849808965.png)
 
Love the typeface! Thank you

**Comment by tarmovannas** [comment]
Thanks
