### ISSUE TITLE
Add italics (for statics) and a Italic axis (for VF)

### ISSUE THREAD

**Issue by cssobral2013** [sora-xor/sora-font#6]

**Comment by cssobral2013** [comment]
@sora-xor - I'm proposing italics and a Medium weight for this font. See them [here](https://github.com/cssobral2013/sora-font/tree/master/sources).
All was made using FontLab version 7.

**Comment by tarmovannas** [comment]
@cssobral2013 Thank you so much! We have confirmed the italics with the original authors of the Sora typeface as well as with the Google Fonts team, and we all feel that your work is very good and within the spirit of the original font. So we are moving ahead with implementing the italics into the Sora project. Thank you so much for your contribution.
